# Generated by Django 4.1.5 on 2023-01-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
